### ISSUE TITLE
Troubles with init script

### ISSUE THREAD

**Issue by junkycoder** [hckr-studio/blendid#305]
```
echo "22" > .nvmrc
nvm install $(< .nvmrc)
yarn set version berry
echo "nodeLinker: node-modules\nenableGlobalCache: false" >> .yarnrc.yml
yarn init
yarn add @hckr_/blendid
yarn blendid init
yarn blendid
Downloading and installing node v22.12.0...
Downloading https://nodejs.org/dist/v22.12.0/node-v22.12.0-darwin-arm64.tar.xz...
############################################################################################################################################################################################################### 100.0%
Computing checksum with shasum -a 256
Checksums matched!
Now using node v22.12.0 (npm v10.9.0)
➤ YN0000: You don't seem to have Corepack enabled; we'll have to rely on yarnPath instead
➤ YN0000: Downloading https://repo.yarnpkg.com/4.5.3/packages/yarnpkg-cli/bin/yarn.js
➤ YN0000: Saving the new release in .yarn/releases/yarn-4.5.3.cjs
➤ YN0000: Done with warnings in 0s 357ms
➤ YN0000: · Yarn 4.5.3
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed
➤ YN0000: · Done in 0s 23ms
➤ YN0000: · Yarn 4.5.3
➤ YN0000: ┌ Resolution step
➤ YN0085: │ + @hckr_/blendid@npm:9.0.0, @csstools/cascade-layer-name-parser@npm:2.0.4, @csstools/color-helpers@npm:5.0.1, @csstools/css-calc@npm:2.1.0, @csstools/css-color-parser@npm:3.0.6, and 644 more.
➤ YN0000: └ Completed in 8s 568ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ 586 packages were added to the project (+ 77.03 MiB).
➤ YN0000: └ Completed in 1s 353ms
➤ YN0000: ┌ Link step
➤ YN0007: │ esbuild@npm:0.24.0 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.21.5 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 1s 700ms
➤ YN0000: · Done in 11s 701ms
Error [ERR_REQUIRE_ASYNC_MODULE]: require() cannot be used on an ESM graph with top-level await. Use import() instead. To see where the top-level await comes from, use --experimental-print-required-tla.
    at ModuleJobSync.runSync (node:internal/modules/esm/module_job:392:13)
    at ModuleLoader.importSyncForRequire (node:internal/modules/esm/loader:329:47)
    at Object.loadESMFromCJS [as .mjs] (node:internal/modules/cjs/loader:1414:24)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:219:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:138:16)
    at requireOrImport (/Users/junkycoder/Developer/fakan/verunkavyrabi.cz/node_modules/gulp-cli/lib/shared/require-or-import.js:20:11) {
  code: 'ERR_REQUIRE_ASYNC_MODULE'
}
Error [ERR_REQUIRE_ASYNC_MODULE]: require() cannot be used on an ESM graph with top-level await. Use import() instead. To see where the top-level await comes from, use --experimental-print-required-tla.
    at ModuleJobSync.runSync (node:internal/modules/esm/module_job:392:13)
    at ModuleLoader.importSyncForRequire (node:internal/modules/esm/loader:329:47)
    at Object.loadESMFromCJS [as .mjs] (node:internal/modules/cjs/loader:1414:24)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:219:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:138:16)
    at requireOrImport (/Users/junkycoder/Developer/fakan/verunkavyrabi.cz/node_modules/gulp-cli/lib/shared/require-or-import.js:20:11) {
  code: 'ERR_REQUIRE_ASYNC_MODULE'
}
```

**Comment by rarous** [comment]
The problem is Node 22.12+ that broke Gulp's require magic. There is an open PR with fix https://github.com/gulpjs/gulp-cli/pull/269. Workaround is to stick with Node.js 22.11. This is why the readme contains this explicit version.
